### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RexWzh** [cubenlp/ChatTool#24]
TODO:

- [ ] add support for the new model: `gpt-4-vision-preview`
- [ ] plan for the assistant https://platform.openai.com/docs/api-reference/assistants

---

   - [x] ~~fix dependency for py3.10(tiktoken failed)~~
   - [x] ~~update token calculator & cost function~~
   - [x] ~~wrapper for the function call~~
   - [x] ~~Add examples to the docs of each `Chat` function(using Copilot).~~
   - [x] ~~Use streamline instead of a simple request(just like [OpenAI.jl](https://github.com/JuliaML/OpenAI.jl))~~
   - [x] ~~Use `asyncio` to process data~~
